word_list = [
    "apple", "giraffe", "piano", "mountain", "electric", "bicycle", "kangaroo", "elephant", "notebook", "chair",
    "penguin", "dragon", "banana", "cupboard", "rainbow", "tiger", "library", "moon", "strawberry", "mountain",
    "juxtapose", "laptop", "coconut", "parrot", "waterfall", "spider", "sandwich", "pyramid", "window", "airplane",
    "guitar", "river", "hospital", "helicopter", "camera", "baker", "zebra", "broccoli", "butterfly", "carpet",
    "bridge", "sunflower", "cloud", "train", "ocean", "chocolate", "squirrel", "carrot", "festival", "volcano",
    "skateboard", "wallet", "island", "alligator", "canyon", "jacket", "pepper", "school", "submarine", "diamond",
    "peach", "sunshine", "forest", "castle", "newspaper", "avocado", "planet", "truck", "penguin", "dinosaur",
    "river", "radio", "mosquito", "lizard", "telephone", "pizza", "telescope", "straw", "watermelon", "mango",
    "star", "whale", "violin", "library", "cucumber", "desert", "city", "telephone", "umbrella", "fountain",
    "salmon", "cloud", "pencil", "cave", "car", "pasta", "coconut", "safari", "glacier", "flamingo", "jellyfish",
    "octopus", "firefighter", "mountain", "cheetah", "owl", "magazine", "donkey", "river", "astronaut", "lighthouse",
    "peanut", "rocket", "eagle", "pancake", "laptop", "garden", "potato", "octopus", "waterfall", "snowflake",
    "peacock", "piano", "koala", "computer", "seashell", "lemon", "caterpillar", "tornado", "meadow", "whale",
    "gorilla", "ladder", "robot", "mushroom", "soap", "basketball", "tractor", "moon", "ladybug", "tiger",
    "airplane", "water", "volcano", "monkey", "garage", "submarine", "spaceship", "rose", "avocado", "computer",
    "helicopter", "banana", "cheese", "turtle", "pyramid", "lamp", "pencil", "earthquake", "sunflower", "guitar",
    "motorcycle", "zebra", "airship", "rainbow", "camera", "plumber", "subway", "mailbox", "cupcake", "television",
    "apple", "mouse", "bridge", "candy", "bookstore", "galaxy", "newspaper", "car", "pigeon", "mirror",
    "airplane", "honey", "cloud", "earth", "kangaroo", "spaceship", "donut", "train", "hurricane", "octopus",
    "violin", "flower", "baseball", "pasta", "owl", "library", "forest", "cabbage", "eagle", "cathedral",
    "skyscraper", "canyon", "giraffe", "garden", "fireplace", "guitar", "tulip", "butterfly", "moon", "hamburger",
    "chicken", "elephant", "dragon", "beach", "park", "airplane", "carrot", "pirate", "boat", "mountain",
    "clock", "pear", "river", "bicycle", "shark", "pizza", "jelly", "sword", "computer", "peanut", "spoon",
    "whale", "notebook", "violin", "baker", "honeybee", "castle", "grape", "telephone", "tiger", "basketball",
    "earth", "lemonade", "ostrich", "star", "volcano", "pepper", "jacket", "lobster", "kitchen", "jungle",
    "sandwich", "astronaut", "rocket", "chocolate", "raccoon", "cheetah", "pear", "sunflower", "zebra", "beaver",
    "octopus", "skateboard", "donkey", "moon", "cave", "umbrella", "firetruck", "bridge", "piano", "hospital",
    "museum", "snowman", "caterpillar", "festival", "river", "eagle", "lamp", "fox", "mountain", "crocodile",
    "book", "giraffe", "iguana", "pear", "peanut", "sailboat", "gorilla", "ocean", "plumber", "toothbrush",
    "rocket", "penguin", "cherry", "cupboard", "radio", "butterfly", "ocean", "umbrella", "telescope", "notebook",
    "pyramid", "mountain", "tomato", "avocado", "lamp", "ladder", "motorcycle", "dolphin", "newspaper", "clock",
    "train", "watermelon", "tornado", "pancake", "mirror", "ship", "airplane", "library", "frog", "pirate",
    "skyscraper", "pyramid", "robot", "piano", "tulip", "apple", "firetruck", "diamond", "laptop", "dragon",
    "starfish", "spaceship", "squirrel", "ocean", "river", "tiger", "potato", "rocket", "pigeon", "library",
    "bridge", "baseball", "island", "pancake", "iceberg", "raccoon", "garden", "spaceship", "canyon", "giraffe",
    "sunshine", "crocodile", "mountain", "waterfall", "camera", "school", "piano", "caterpillar", "fountain", "hamburger",
    "airplane"
]

alphabet = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']